name : simple-pos
services:
  db:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootme
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
    - '27017:27017'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
